'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17626
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyCompany("RandomSig"),  _
 Assembly: AssemblyCopyright("Copyright © K4GDW Software 2012"),  _
 Assembly: AssemblyTrademark("K4GDW Software"),  _
 Assembly: AssemblyProduct("RandomSig"),  _
 Assembly: ComVisible(false),  _
 Assembly: AssemblyVersion("2.0"),  _
 Assembly: AssemblyFileVersion("2.0.1"),  _
 Assembly: AssemblyInformationalVersion("2.0.1 ")> 

